name: My first workflow

on:
    push:
        branches: [main]
    pull_request:
        # The branches below must be a subset of the branches above
        branches: [main]

jobs:
    Job1:
        runs-on: ubuntu-latest
        steps:
            - run: echo "This is Job 1!"
        needs: [Job5, Job2]
    Job2:
        runs-on: ubuntu-latest
        steps:
            - run: echo "This is Job 2!"
        needs: [Job5]
    Job3:
        runs-on: ubuntu-latest
        steps:
            - run: echo "This is Job 3!"
        needs: [Job4]
    Job4:
        runs-on: ubuntu-latest
        steps:
            - run: echo "This is Job 4!"
    Job5:
        runs-on: ubuntu-latest
        steps:
            - run: echo "This is Job 5!"
        needs: [Job4]
